import type { CurriculumConcept } from './curriculum';

// Gerado a partir do Outline Completo — Curso OAB 1ª Fase (agosto/2026).
// Cada tema numerado (x.y) vira uma unidade curricular do motor.
type Row = [string, string, string, number, string, number];

const ROWS: Row[] = [
  ["m01-t01-natureza-da-advocacia-e-atividade-privativa", "Natureza da advocacia e atividade privativa", "Ética Profissional", 1, "", 1.0],
  ["m01-t02-inscricao-estagio-e-sociedade", "Inscrição, estágio e sociedade", "Ética Profissional", 2, "m01-t01-natureza-da-advocacia-e-atividade-privativa", 1.0],
  ["m01-t03-direitos-prerrogativas-e-inviolabilidades", "Direitos, prerrogativas e inviolabilidades", "Ética Profissional", 3, "m01-t02-inscricao-estagio-e-sociedade", 1.0],
  ["m01-t04-incompatibilidades-e-impedimentos", "Incompatibilidades e impedimentos", "Ética Profissional", 4, "m01-t03-direitos-prerrogativas-e-inviolabilidades", 1.0],
  ["m01-t05-honorarios-advocaticios", "Honorários advocatícios", "Ética Profissional", 5, "m01-t04-incompatibilidades-e-impedimentos", 1.0],
  ["m01-t06-publicidade-e-deveres-eticos", "Publicidade e deveres éticos", "Ética Profissional", 6, "m01-t05-honorarios-advocaticios", 0.72],
  ["m01-t07-infracoes-disciplinares-e-processo", "Infrações disciplinares e processo", "Ética Profissional", 7, "m01-t06-publicidade-e-deveres-eticos", 1.0],
  ["m01-t08-orgaos-da-oab-e-eleicoes", "Órgãos da OAB e eleições", "Ética Profissional", 8, "m01-t07-infracoes-disciplinares-e-processo", 0.72],
  ["m02-t01-jusnaturalismo", "Jusnaturalismo", "Filosofia do Direito", 1, "", 1.0],
  ["m02-t02-juspositivismo", "Juspositivismo", "Filosofia do Direito", 2, "m02-t01-jusnaturalismo", 1.0],
  ["m02-t03-realismo-sociologia-e-pragmatismo", "Realismo, sociologia e pragmatismo", "Filosofia do Direito", 3, "m02-t02-juspositivismo", 0.72],
  ["m02-t04-tradicoes-contemporaneas", "Tradições contemporâneas", "Filosofia do Direito", 4, "m02-t03-realismo-sociologia-e-pragmatismo", 0.72],
  ["m02-t05-interpretacao-e-argumentacao", "Interpretação e argumentação", "Filosofia do Direito", 5, "m02-t04-tradicoes-contemporaneas", 0.72],
  ["m02-t06-justica-e-teorias-politicas", "Justiça e teorias políticas", "Filosofia do Direito", 6, "m02-t05-interpretacao-e-argumentacao", 0.45],
  ["m03-t01-constitucionalismo-constituicao-e-hermeneutica", "Constitucionalismo, Constituição e hermenêutica", "Direito Constitucional", 1, "", 0.72],
  ["m03-t02-principios-fundamentais-arts-1o4o", "Princípios fundamentais (arts. 1º–4º)", "Direito Constitucional", 2, "m03-t01-constitucionalismo-constituicao-e-hermeneutica", 1.0],
  ["m03-t03-direitos-e-garantias-fundamentais-art-5o", "Direitos e garantias fundamentais (art. 5º)", "Direito Constitucional", 3, "m03-t02-principios-fundamentais-arts-1o4o", 1.0],
  ["m03-t04-remedios-constitucionais", "Remédios constitucionais", "Direito Constitucional", 4, "m03-t03-direitos-e-garantias-fundamentais-art-5o", 1.0],
  ["m03-t05-organizacao-do-estado-e-competencias", "Organização do Estado e competências", "Direito Constitucional", 5, "m03-t04-remedios-constitucionais", 1.0],
  ["m03-t06-administracao-publica-na-cf-art-37-e-ss", "Administração Pública na CF (art. 37 e ss.)", "Direito Constitucional", 6, "m03-t05-organizacao-do-estado-e-competencias", 0.72],
  ["m03-t07-poder-legislativo", "Poder Legislativo", "Direito Constitucional", 7, "m03-t06-administracao-publica-na-cf-art-37-e-ss", 1.0],
  ["m03-t08-poder-executivo", "Poder Executivo", "Direito Constitucional", 8, "m03-t07-poder-legislativo", 1.0],
  ["m03-t09-poder-judiciario", "Poder Judiciário", "Direito Constitucional", 9, "m03-t08-poder-executivo", 1.0],
  ["m03-t10-controle-de-constitucionalidade", "Controle de constitucionalidade", "Direito Constitucional", 10, "m03-t09-poder-judiciario", 1.0],
  ["m03-t11-defesa-do-estado-ordem-economica-e-social", "Defesa do Estado, ordem econômica e social", "Direito Constitucional", 11, "m03-t10-controle-de-constitucionalidade", 0.72],
  ["m04-t01-teoria-geral", "Teoria geral", "Direitos Humanos", 1, "", 1.0],
  ["m04-t02-sistema-onu", "Sistema ONU", "Direitos Humanos", 2, "m04-t01-teoria-geral", 0.72],
  ["m04-t03-sistema-interamericano", "Sistema Interamericano", "Direitos Humanos", 3, "m04-t02-sistema-onu", 1.0],
  ["m04-t04-dh-no-direito-interno", "DH no direito interno", "Direitos Humanos", 4, "m04-t03-sistema-interamericano", 1.0],
  ["m05-t01-principios-e-direitos-politicos", "Princípios e direitos políticos", "Direito Eleitoral", 1, "", 1.0],
  ["m05-t02-sistemas-eleitorais-e-organizacao", "Sistemas eleitorais e organização", "Direito Eleitoral", 2, "m05-t01-principios-e-direitos-politicos", 0.72],
  ["m05-t03-inelegibilidades-e-ficha-limpa", "Inelegibilidades e Ficha Limpa", "Direito Eleitoral", 3, "m05-t02-sistemas-eleitorais-e-organizacao", 1.0],
  ["m05-t04-partidos-propaganda-e-financiamento", "Partidos, propaganda e financiamento", "Direito Eleitoral", 4, "m05-t03-inelegibilidades-e-ficha-limpa", 1.0],
  ["m05-t05-acoes-recursos-e-crimes", "Ações, recursos e crimes", "Direito Eleitoral", 5, "m05-t04-partidos-propaganda-e-financiamento", 0.72],
  ["m06-t01-direito-internacional-publico", "Direito Internacional Público", "Direito Internacional", 1, "", 1.0],
  ["m06-t02-direito-internacional-privado", "Direito Internacional Privado", "Direito Internacional", 2, "m06-t01-direito-internacional-publico", 1.0],
  ["m07-t01-atividade-financeira-e-orcamento", "Atividade financeira e orçamento", "Direito Financeiro", 1, "", 1.0],
  ["m07-t02-receitas-transferencias-e-precatorios", "Receitas, transferências e precatórios", "Direito Financeiro", 2, "m07-t01-atividade-financeira-e-orcamento", 0.72],
  ["m07-t03-lrf-divida-e-vedacoes", "LRF, dívida e vedações", "Direito Financeiro", 3, "m07-t02-receitas-transferencias-e-precatorios", 1.0],
  ["m08-t01-especies-tributarias-e-competencia", "Espécies tributárias e competência", "Direito Tributário", 1, "", 1.0],
  ["m08-t02-principios-constitucionais-tributarios", "Princípios constitucionais tributários", "Direito Tributário", 2, "m08-t01-especies-tributarias-e-competencia", 1.0],
  ["m08-t03-obrigacao-credito-lancamento", "Obrigação, crédito, lançamento", "Direito Tributário", 3, "m08-t02-principios-constitucionais-tributarios", 1.0],
  ["m08-t04-administracao-paf-e-execucao-fiscal", "Administração, PAF e execução fiscal", "Direito Tributário", 4, "m08-t03-obrigacao-credito-lancamento", 0.72],
  ["m08-t05-tributos-em-especie-pontos-de-prova", "Tributos em espécie — pontos de prova", "Direito Tributário", 5, "m08-t04-administracao-paf-e-execucao-fiscal", 0.72],
  ["m09-t01-regime-juridico-e-principios", "Regime jurídico e princípios", "Direito Administrativo", 1, "", 1.0],
  ["m09-t02-organizacao-administrativa", "Organização administrativa", "Direito Administrativo", 2, "m09-t01-regime-juridico-e-principios", 1.0],
  ["m09-t03-atos-administrativos", "Atos administrativos", "Direito Administrativo", 3, "m09-t02-organizacao-administrativa", 1.0],
  ["m09-t04-poderes-administrativos", "Poderes administrativos", "Direito Administrativo", 4, "m09-t03-atos-administrativos", 1.0],
  ["m09-t05-agentes-publicos", "Agentes públicos", "Direito Administrativo", 5, "m09-t04-poderes-administrativos", 1.0],
  ["m09-t06-licitacoes-e-contratos", "Licitações e contratos", "Direito Administrativo", 6, "m09-t05-agentes-publicos", 1.0],
  ["m09-t07-servicos-publicos", "Serviços públicos", "Direito Administrativo", 7, "m09-t06-licitacoes-e-contratos", 0.72],
  ["m09-t08-intervencao-na-propriedade", "Intervenção na propriedade", "Direito Administrativo", 8, "m09-t07-servicos-publicos", 1.0],
  ["m09-t09-responsabilidade-civil-do-estado", "Responsabilidade civil do Estado", "Direito Administrativo", 9, "m09-t08-intervencao-na-propriedade", 1.0],
  ["m09-t10-improbidade-administrativa", "Improbidade administrativa", "Direito Administrativo", 10, "m09-t09-responsabilidade-civil-do-estado", 1.0],
  ["m09-t11-processo-administrativo-e-controle", "Processo administrativo e controle", "Direito Administrativo", 11, "m09-t10-improbidade-administrativa", 0.72],
  ["m10-t01-fundamentos-e-principios", "Fundamentos e princípios", "Direito Ambiental", 1, "", 1.0],
  ["m10-t02-instrumentos-de-protecao", "Instrumentos de proteção", "Direito Ambiental", 2, "m10-t01-fundamentos-e-principios", 1.0],
  ["m10-t03-responsabilidade-ambiental", "Responsabilidade ambiental", "Direito Ambiental", 3, "m10-t02-instrumentos-de-protecao", 1.0],
  ["m11-t01-lei-de-introducao-e-parte-geral-pessoa-natural", "Lei de Introdução e Parte Geral — pessoa natural", "Direito Civil", 1, "", 1.0],
  ["m11-t02-pessoa-juridica", "Pessoa jurídica", "Direito Civil", 2, "m11-t01-lei-de-introducao-e-parte-geral-pessoa-natural", 0.72],
  ["m11-t03-bens", "Bens", "Direito Civil", 3, "m11-t02-pessoa-juridica", 0.72],
  ["m11-t04-fatos-atos-e-negocios-juridicos", "Fatos, atos e negócios jurídicos", "Direito Civil", 4, "m11-t03-bens", 1.0],
  ["m11-t05-prescricao-e-decadencia", "Prescrição e decadência", "Direito Civil", 5, "m11-t04-fatos-atos-e-negocios-juridicos", 1.0],
  ["m11-t06-obrigacoes", "Obrigações", "Direito Civil", 6, "m11-t05-prescricao-e-decadencia", 1.0],
  ["m11-t07-contratos", "Contratos", "Direito Civil", 7, "m11-t06-obrigacoes", 1.0],
  ["m11-t08-responsabilidade-civil", "Responsabilidade civil", "Direito Civil", 8, "m11-t07-contratos", 1.0],
  ["m11-t09-direitos-reais", "Direitos reais", "Direito Civil", 9, "m11-t08-responsabilidade-civil", 1.0],
  ["m11-t10-familia", "Família", "Direito Civil", 10, "m11-t09-direitos-reais", 1.0],
  ["m11-t11-sucessoes", "Sucessões", "Direito Civil", 11, "m11-t10-familia", 1.0],
  ["m12-t01-doutrina-da-protecao-integral", "Doutrina da proteção integral", "ECA", 1, "", 1.0],
  ["m12-t02-familia-guarda-tutela-adocao", "Família, guarda, tutela, adoção", "ECA", 2, "m12-t01-doutrina-da-protecao-integral", 1.0],
  ["m12-t03-ato-infracional-e-medidas", "Ato infracional e medidas", "ECA", 3, "m12-t02-familia-guarda-tutela-adocao", 1.0],
  ["m12-t04-conselho-tutelar-justica-e-crimes", "Conselho Tutelar, justiça e crimes", "ECA", 4, "m12-t03-ato-infracional-e-medidas", 0.72],
  ["m13-t01-relacao-de-consumo", "Relação de consumo", "Direito do Consumidor", 1, "", 1.0],
  ["m13-t02-principios-e-direitos-basicos", "Princípios e direitos básicos", "Direito do Consumidor", 2, "m13-t01-relacao-de-consumo", 1.0],
  ["m13-t03-responsabilidade-pelo-fato-e-pelo-vicio", "Responsabilidade pelo fato e pelo vício", "Direito do Consumidor", 3, "m13-t02-principios-e-direitos-basicos", 1.0],
  ["m13-t04-superendividamento-credito-e-tutela", "Superendividamento, crédito e tutela", "Direito do Consumidor", 4, "m13-t03-responsabilidade-pelo-fato-e-pelo-vicio", 0.72],
  ["m14-t01-empresario-e-estabelecimento", "Empresário e estabelecimento", "Direito Empresarial", 1, "", 1.0],
  ["m14-t02-sociedades", "Sociedades", "Direito Empresarial", 2, "m14-t01-empresario-e-estabelecimento", 1.0],
  ["m14-t03-titulos-de-credito", "Títulos de crédito", "Direito Empresarial", 3, "m14-t02-sociedades", 1.0],
  ["m14-t04-recuperacao-e-falencia", "Recuperação e falência", "Direito Empresarial", 4, "m14-t03-titulos-de-credito", 1.0],
  ["m14-t05-propriedade-industrial-marco-e-contratos-mercantis", "Propriedade industrial, MARCO e contratos mercantis", "Direito Empresarial", 5, "m14-t04-recuperacao-e-falencia", 0.72],
  ["m15-t01-normas-fundamentais-e-competencia", "Normas fundamentais e competência", "Processo Civil", 1, "", 1.0],
  ["m15-t02-sujeitos-litisconsorcio-intervencao", "Sujeitos, litisconsórcio, intervenção", "Processo Civil", 2, "m15-t01-normas-fundamentais-e-competencia", 0.72],
  ["m15-t03-atos-prazos-tutelas", "Atos, prazos, tutelas", "Processo Civil", 3, "m15-t02-sujeitos-litisconsorcio-intervencao", 1.0],
  ["m15-t04-formacao-suspensao-extincao-e-procedimento-comum", "Formação, suspensão, extinção e procedimento comum", "Processo Civil", 4, "m15-t03-atos-prazos-tutelas", 0.72],
  ["m15-t05-cumprimento-de-sentenca-e-execucao", "Cumprimento de sentença e execução", "Processo Civil", 5, "m15-t04-formacao-suspensao-extincao-e-procedimento-comum", 1.0],
  ["m15-t06-procedimentos-especiais-de-maior-incidencia", "Procedimentos especiais de maior incidência", "Processo Civil", 6, "m15-t05-cumprimento-de-sentenca-e-execucao", 0.72],
  ["m15-t07-recursos-e-precedentes", "Recursos e precedentes", "Processo Civil", 7, "m15-t06-procedimentos-especiais-de-maior-incidencia", 1.0],
  ["m16-t01-lei-penal-no-tempo-e-no-espaco", "Lei penal no tempo e no espaço", "Direito Penal", 1, "", 1.0],
  ["m16-t02-teoria-do-crime", "Teoria do crime", "Direito Penal", 2, "m16-t01-lei-penal-no-tempo-e-no-espaco", 1.0],
  ["m16-t03-teoria-da-pena-e-extincao-da-punibilidade", "Teoria da pena e extinção da punibilidade", "Direito Penal", 3, "m16-t02-teoria-do-crime", 1.0],
  ["m16-t04-crimes-em-especie-pessoa-e-vida", "Crimes em espécie — Pessoa e vida", "Direito Penal", 4, "m16-t03-teoria-da-pena-e-extincao-da-punibilidade", 1.0],
  ["m16-t05-crimes-contra-o-patrimonio", "Crimes contra o patrimônio", "Direito Penal", 5, "m16-t04-crimes-em-especie-pessoa-e-vida", 1.0],
  ["m16-t06-crimes-contra-a-administracao-fe-publica-e-outros-de-al", "Crimes contra a Administração, fé pública e outros de alta", "Direito Penal", 6, "m16-t05-crimes-contra-o-patrimonio", 0.72],
  ["m17-t01-sistemas-principios-e-inquerito", "Sistemas, princípios e inquérito", "Processo Penal", 1, "", 1.0],
  ["m17-t02-acao-penal-e-acao-civil-ex-delicto", "Ação penal e ação civil ex delicto", "Processo Penal", 2, "m17-t01-sistemas-principios-e-inquerito", 1.0],
  ["m17-t03-competencia-e-sujeito-processuais", "Competência e sujeito processuais", "Processo Penal", 3, "m17-t02-acao-penal-e-acao-civil-ex-delicto", 1.0],
  ["m17-t04-provas", "Provas", "Processo Penal", 4, "m17-t03-competencia-e-sujeito-processuais", 1.0],
  ["m17-t05-prisoes-e-medidas-cautelares", "Prisões e medidas cautelares", "Processo Penal", 5, "m17-t04-provas", 1.0],
  ["m17-t06-procedimentos", "Procedimentos", "Processo Penal", 6, "m17-t05-prisoes-e-medidas-cautelares", 0.72],
  ["m17-t07-recursos-acoes-autonomas-e-execucao", "Recursos, ações autônomas e execução", "Processo Penal", 7, "m17-t06-procedimentos", 1.0],
  ["m18-t01-seguridade-e-rgps", "Seguridade e RGPS", "Direito Previdenciário", 1, "", 1.0],
  ["m18-t02-segurados-e-dependentes", "Segurados e dependentes", "Direito Previdenciário", 2, "m18-t01-seguridade-e-rgps", 1.0],
  ["m18-t03-beneficios", "Benefícios", "Direito Previdenciário", 3, "m18-t02-segurados-e-dependentes", 1.0],
  ["m19-t01-principios-e-relacao-de-emprego", "Princípios e relação de emprego", "Direito do Trabalho", 1, "", 1.0],
  ["m19-t02-contrato-duracao-e-salario", "Contrato, duração e salário", "Direito do Trabalho", 2, "m19-t01-principios-e-relacao-de-emprego", 1.0],
  ["m19-t03-interrupcao-suspensao-e-extincao", "Interrupção, suspensão e extinção", "Direito do Trabalho", 3, "m19-t02-contrato-duracao-e-salario", 1.0],
  ["m19-t04-saude-menores-mulheres-e-nao-discriminacao", "Saúde, menores, mulheres e não discriminação", "Direito do Trabalho", 4, "m19-t03-interrupcao-suspensao-e-extincao", 0.72],
  ["m19-t05-direito-coletivo", "Direito coletivo", "Direito do Trabalho", 5, "m19-t04-saude-menores-mulheres-e-nao-discriminacao", 0.72],
  ["m20-t01-principios-organizacao-e-competencia", "Princípios, organização e competência", "Processo do Trabalho", 1, "", 1.0],
  ["m20-t02-atos-prazos-e-partes", "Atos, prazos e partes", "Processo do Trabalho", 2, "m20-t01-principios-organizacao-e-competencia", 0.72],
  ["m20-t03-rito-peticao-audiencia-e-provas", "Rito, petição, audiência e provas", "Processo do Trabalho", 3, "m20-t02-atos-prazos-e-partes", 1.0],
  ["m20-t04-recursos-trabalhistas", "Recursos trabalhistas", "Processo do Trabalho", 4, "m20-t03-rito-peticao-audiencia-e-provas", 1.0],
  ["m20-t05-execucao-trabalhista-e-procedimentos-especiais", "Execução trabalhista e procedimentos especiais", "Processo do Trabalho", 5, "m20-t04-recursos-trabalhistas", 1.0],
];

export const OAB_OUTLINE_CURRICULUM: CurriculumConcept[] = ROWS.map(
  ([id, label, subject, order, prerequisite, incidenceWeight]) => ({
    id,
    label,
    subject,
    order,
    prerequisites: prerequisite ? [prerequisite] : [],
    unlockStrength: prerequisite ? 0.52 : 0,
    incidenceWeight,
  }),
);